# 1. Pandas Basics - Temel Alıştırmalar

In [1]:
import pandas as pd

In [3]:
import pandas as pd

veriler = {
    "İsim": ["Ayşe", "Mehmet", "Zeynep", "Ali", "Ece"],
    "Yaş": [21, 24, 22, 25, 20],
    "Bölüm": ["Matematik", "Fizik", "Matematik", "Kimya", "Fizik"],
    "Not": [85, 70, 95, 60, 90]
}

In [9]:
df = pd.DataFrame(veriler)

In [11]:
df

     İsim  Yaş      Bölüm  Not
0    Ayşe   21  Matematik   85
1  Mehmet   24      Fizik   70
2  Zeynep   22  Matematik   95
3     Ali   25      Kimya   60
4     Ece   20      Fizik   90

In [15]:
df.head() #ilk 5 satırı gosterir

     İsim  Yaş      Bölüm  Not
0    Ayşe   21  Matematik   85
1  Mehmet   24      Fizik   70
2  Zeynep   22  Matematik   95
3     Ali   25      Kimya   60
4     Ece   20      Fizik   90

In [17]:
df.tail() #son 5 satırı gosterir

     İsim  Yaş      Bölüm  Not
0    Ayşe   21  Matematik   85
1  Mehmet   24      Fizik   70
2  Zeynep   22  Matematik   95
3     Ali   25      Kimya   60
4     Ece   20      Fizik   90

In [21]:
df.shape # kaça kaç matris olduğunu gösterir (satır x sütun)

(5, 4)

In [27]:
df.columns #sütun isimlerini gösterir

Index(['İsim', 'Yaş', 'Bölüm', 'Not'], dtype='object')

In [33]:
df.info() #sütunların veri tiplerini ve doluluk durumunu gösterir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   İsim    5 non-null      object
 1   Yaş     5 non-null      int64
 2   Bölüm   5 non-null      object
 3   Not     5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [35]:
df.describe() #sayısal sütunların özet istatistiklerini verir

             Yaş       Not
count   5.000000   5.00000
mean   22.400000  80.00000
std     2.073644  14.57738
min    20.000000  60.00000
25%    21.000000  70.00000
50%    22.000000  85.00000
75%    24.000000  90.00000
max    25.000000  95.00000

In [39]:
df["İsim"] #isim sütununu seçer

0      Ayşe
1    Mehmet
2    Zeynep
3       Ali
4       Ece
Name: İsim, dtype: object

In [45]:
df[0:3] #veya df.head(3) şeklinde de yapılabilirdi

     İsim  Yaş      Bölüm  Not
0    Ayşe   21  Matematik   85
1  Mehmet   24      Fizik   70
2  Zeynep   22  Matematik   95

In [47]:
df.tail(2)

  İsim  Yaş  Bölüm  Not
3  Ali   25  Kimya   60
4  Ece   20  Fizik   90

In [55]:
df["Not"]

0    85
1    70
2    95
3    60
4    90
Name: Not, dtype: int64

In [63]:
df[["Yaş" , "Not"]] #sadece yaş ve not sütunlarını birlikte gösterdim

   Yaş  Not
0   21   85
1   24   70
2   22   95
3   25   60
4   20   90

In [65]:
df["Not"].mean()

80.0

In [67]:
df["Not"].max()

95

In [69]:
df["Yaş"].min()

20

# 2. Pandas - Satır Seçme ve Filtreleme

In [75]:
#loc >> indeks etiketine göre seçim yapar
#iloc >> satırın veya sütunun sayısal konumuna göre seçim yapar

In [77]:
df

     İsim  Yaş      Bölüm  Not
0    Ayşe   21  Matematik   85
1  Mehmet   24      Fizik   70
2  Zeynep   22  Matematik   95
3     Ali   25      Kimya   60
4     Ece   20      Fizik   90

In [81]:
df.loc[1] #indeksi 1 olan satırı getirir

İsim     Mehmet
Yaş          24
Bölüm     Fizik
Not          70
Name: 1, dtype: object

In [85]:
df.iloc[3] #tablonun 3. satırını getirir

İsim       Ali
Yaş         25
Bölüm    Kimya
Not         60
Name: 3, dtype: object

In [93]:
df[df["Yaş"] > 22]

     İsim  Yaş  Bölüm  Not
1  Mehmet   24  Fizik   70
3     Ali   25  Kimya   60

In [95]:
df[df["Not"] > 80]

     İsim  Yaş      Bölüm  Not
0    Ayşe   21  Matematik   85
2  Zeynep   22  Matematik   95
4     Ece   20      Fizik   90

In [103]:
df [df["Bölüm"] == "Matematik"]

     İsim  Yaş      Bölüm  Not
0    Ayşe   21  Matematik   85
2  Zeynep   22  Matematik   95

In [105]:
df.sort_values("Not")

     İsim  Yaş      Bölüm  Not
3     Ali   25      Kimya   60
1  Mehmet   24      Fizik   70
0    Ayşe   21  Matematik   85
4     Ece   20      Fizik   90
2  Zeynep   22  Matematik   95

In [114]:
df[df["Yaş"] <= 22][["İsim" , "Yaş"]]

     İsim  Yaş
0    Ayşe   21
2  Zeynep   22
4     Ece   20

In [116]:
df[df["Not"] > 80][["İsim" , "Not"]]

     İsim  Not
0    Ayşe   85
2  Zeynep   95
4     Ece   90

In [118]:
df.loc[df["Not"].idxmax()] #idxmax en yüksek değerin bulunduğu indeks etiketini verir

İsim        Zeynep
Yaş             22
Bölüm    Matematik
Not             95
Name: 2, dtype: object

In [122]:
df.sort_values("Not" , ascending = False).head(1) #ascending=False sıralamanın azalan şeklinde yapmasını sağlar

     İsim  Yaş      Bölüm  Not
2  Zeynep   22  Matematik   95

In [126]:
en_yuksek_not = df["Not"].max()
df[df["Not"] == en_yuksek_not ]

     İsim  Yaş      Bölüm  Not
2  Zeynep   22  Matematik   95

In [128]:
df["Geçti mi"] = df["Not"] >= 70

In [130]:
df

     İsim  Yaş      Bölüm  Not  Geçti mi
0    Ayşe   21  Matematik   85      True
1  Mehmet   24      Fizik   70      True
2  Zeynep   22  Matematik   95      True
3     Ali   25      Kimya   60     False
4     Ece   20      Fizik   90      True

In [136]:
df["Başarılı mı?"] = df["Not"] > 80

In [138]:
df

     İsim  Yaş      Bölüm  Not  Geçti mi  Başarılı  Başarılı mı?
0    Ayşe   21  Matematik   85      True      True          True
1  Mehmet   24      Fizik   70      True     False         False
2  Zeynep   22  Matematik   95      True      True          True
3     Ali   25      Kimya   60     False     False         False
4     Ece   20      Fizik   90      True      True          True

In [152]:
df[(df["Not"] > 80) & (df["Yaş"] < 22)]

   İsim  Yaş      Bölüm  Not  Geçti mi  Başarılı  Başarılı mı?
0  Ayşe   21  Matematik   85      True      True          True
4   Ece   20      Fizik   90      True      True          True

In [158]:
df[(df["Not"]  < 80) & (df["Yaş"] < 25 )]

     İsim  Yaş  Bölüm  Not  Geçti mi  Başarılı  Başarılı mı?
1  Mehmet   24  Fizik   70      True     False         False

In [160]:
df[(df["Not"] > 90) | (df["Yaş" ] < 21)]

     İsim  Yaş      Bölüm  Not  Geçti mi  Başarılı  Başarılı mı?
2  Zeynep   22  Matematik   95      True      True          True
4     Ece   20      Fizik   90      True      True          True

In [164]:
df[(df["Not"] >= 70) & (df["Yaş"] >= 23)][["İsim" , "Not" ]]

     İsim  Not
1  Mehmet   70

# Pandas- Veri Düzenleme

In [171]:
df

     İsim  Yaş      Bölüm  Not  Geçti mi  Başarılı  Başarılı mı?
0    Ayşe   21  Matematik   85      True      True          True
1  Mehmet   24      Fizik   70      True     False         False
2  Zeynep   22  Matematik   95      True      True          True
3     Ali   25      Kimya   60     False     False         False
4     Ece   20      Fizik   90      True      True          True

In [167]:
df["Başarılı"] = df["Not"] > 80

In [169]:
df

     İsim  Yaş      Bölüm  Not  Geçti mi  Başarılı  Başarılı mı?
0    Ayşe   21  Matematik   85      True      True          True
1  Mehmet   24      Fizik   70      True     False         False
2  Zeynep   22  Matematik   95      True      True          True
3     Ali   25      Kimya   60     False     False         False
4     Ece   20      Fizik   90      True      True          True

In [215]:
df["Not + 5 " ] = df["Not"] + 5

In [217]:
df

,İsim,Yaş,Bölüm,Not,Geçti mi,Başarılı,Başarılı mı?,Not + 5,Yaş + 1,Çift Not,Geçti,Sonuç
0,Ayşe,21,Matematik,85,True,True,True,90,22,170,True,Geçti
1,Mehmet,24,Fizik,70,True,False,False,75,25,140,False,Geçti
2,Zeynep,22,Matematik,95,True,True,True,100,23,190,True,Geçti
3,Ali,25,Kimya,60,False,False,False,65,26,120,False,Kaldı
4,Ece,20,Fizik,90,True,True,True,95,21,180,True,Geçti

In [177]:
df["Yaş + 1"] = df["Yaş"] + 1

In [179]:
df

,İsim,Yaş,Bölüm,Not,Geçti mi,Başarılı,Başarılı mı?,Not + 5,Yaş + 1
0,Ayşe,21,Matematik,85,True,True,True,90,22
1,Mehmet,24,Fizik,70,True,False,False,75,25
2,Zeynep,22,Matematik,95,True,True,True,100,23
3,Ali,25,Kimya,60,False,False,False,65,26
4,Ece,20,Fizik,90,True,True,True,95,21

In [181]:
df["Çift Not"] = df["Not"] * 2

In [183]:
df

,İsim,Yaş,Bölüm,Not,Geçti mi,Başarılı,Başarılı mı?,Not + 5,Yaş + 1,Çift Not
0,Ayşe,21,Matematik,85,True,True,True,90,22,170
1,Mehmet,24,Fizik,70,True,False,False,75,25,140
2,Zeynep,22,Matematik,95,True,True,True,100,23,190
3,Ali,25,Kimya,60,False,False,False,65,26,120
4,Ece,20,Fizik,90,True,True,True,95,21,180

In [191]:
def sonuc_bul(not_degeri):
    if not_degeri >= 70:
        return "Geçti"
    else:
        return "Kaldı"

In [199]:
df["Sonuç"] = df["Not"].apply(sonuc_bul) #apply() , bir fonksiyonu sütundaki her bir değere tek tek uygular

In [219]:
df

,İsim,Yaş,Bölüm,Not,Geçti mi,Başarılı,Başarılı mı?,Not + 5,Yaş + 1,Çift Not,Geçti,Sonuç
0,Ayşe,21,Matematik,85,True,True,True,90,22,170,True,Geçti
1,Mehmet,24,Fizik,70,True,False,False,75,25,140,False,Geçti
2,Zeynep,22,Matematik,95,True,True,True,100,23,190,True,Geçti
3,Ali,25,Kimya,60,False,False,False,65,26,120,False,Kaldı
4,Ece,20,Fizik,90,True,True,True,95,21,180,True,Geçti

In [221]:
df["Not + 5"] = df["Not"] + 5

In [223]:
en_yuksek_nott = df["Not + 5"].max()
df[df["Not + 5"] == en_yuksek_nott]

,İsim,Yaş,Bölüm,Not,Geçti mi,Başarılı,Başarılı mı?,Not + 5,Yaş + 1,Çift Not,Geçti,Sonuç,Not + 5
2,Zeynep,22,Matematik,95,True,True,True,100,23,190,True,Geçti,100

# 4. Eksik Veriler ve Veri Temizleme

In [226]:
#isnull() >> eksik değerleri bulma
#isnull().sum() >> her sütundaki eksik değerleri sayma
#dropna() >> eksik değer içeren satırları silme
#fillna() >> eksik değerleri doldurma

In [232]:
veriler_eksik = {
    "İsim": ["Ayşe", "Mehmet", "Zeynep", "Ali", "Ece"],
    "Yaş": [21, None, 22, 25, None],
    "Not": [85, 70, None, 60, 90]
}

df_eksik = pd.DataFrame(veriler_eksik)

In [234]:
df_eksik

     İsim   Yaş   Not
0    Ayşe  21.0  85.0
1  Mehmet   NaN  70.0
2  Zeynep  22.0   NaN
3     Ali  25.0  60.0
4     Ece   NaN  90.0

In [236]:
df_eksik.isnull()

    İsim    Yaş    Not
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [238]:
df_eksik.isnull().sum()

İsim    0
Yaş     2
Not     1
dtype: int64

In [240]:
df_eksik.dropna()

   İsim   Yaş   Not
0  Ayşe  21.0  85.0
3   Ali  25.0  60.0

In [242]:
df_eksik.fillna(0)

     İsim   Yaş   Not
0    Ayşe  21.0  85.0
1  Mehmet   0.0  70.0
2  Zeynep  22.0   0.0
3     Ali  25.0  60.0
4     Ece   0.0  90.0

In [246]:
df_dolu =df_eksik["Yaş"].fillna(22)

In [248]:
df_dolu

0    21.0
1    22.0
2    22.0
3    25.0
4    22.0
Name: Yaş, dtype: float64

In [262]:
df_eksik["Not"].fillna(df_eksik["Not"].mean())

0    85.00
1    70.00
2    76.25
3    60.00
4    90.00
Name: Not, dtype: float64

In [264]:
df_dolu = df_eksik.copy()
df_dolu["Yaş"] = df_dolu["Yaş"].fillna(22)
df_dolu["Not"] = df_dolu["Not"].fillna(df_dolu["Not"].mean())

In [268]:
#duplicated() >> tekrarlanan satırları tespit eder
#drop_duplicates() >> tekrarlanan satırları kaldırır

In [270]:
veriler_tekrar = {
    "İsim": ["Ayşe", "Mehmet", "Ayşe", "Ali", "Mehmet"],
    "Yaş": [21, 24, 21, 25, 24],
    "Not": [85, 70, 85, 60, 70]
}

df_tekrar = pd.DataFrame(veriler_tekrar)

In [272]:
df_tekrar

     İsim  Yaş  Not
0    Ayşe   21   85
1  Mehmet   24   70
2    Ayşe   21   85
3     Ali   25   60
4  Mehmet   24   70

In [274]:
df_tekrar.duplicated()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [276]:
df_tekrar.duplicated().sum()

2

In [278]:
df_tekrar.drop_duplicates()

     İsim  Yaş  Not
0    Ayşe   21   85
1  Mehmet   24   70
3     Ali   25   60

# 5. Gruplama ve Özel İstatistikler

In [287]:
calisanlar = {
    "İsim": ["Ayşe", "Mehmet", "Zeynep", "Ali", "Ece", "Can", "Elif"],
    "Departman": ["Veri", "İK", "Veri", "Finans", "İK", "Veri", "Finans"],
    "Maaş": [35000, 28000, 42000, 32000, 30000, 39000, 34000],
    "Deneyim": [2, 1, 4, 3, 2, 3, 2]
}

df_calisan = pd.DataFrame(calisanlar)

In [289]:
df_calisan

     İsim Departman   Maaş  Deneyim
0    Ayşe      Veri  35000        2
1  Mehmet        İK  28000        1
2  Zeynep      Veri  42000        4
3     Ali    Finans  32000        3
4     Ece        İK  30000        2
5     Can      Veri  39000        3
6    Elif    Finans  34000        2

In [285]:
#value_counts >> bir sütundaki her farklı değerin kaç kez tekrarlandığını  sayar

In [293]:
df_calisan["Departman"].value_counts()

Departman
Veri      3
İK        2
Finans    2
Name: count, dtype: int64

In [295]:
#groupby >> verileri belirli kategorilere göre gruplayıp
#özet istatistikler (ortalama, toplam, sayım vb.) çıkarmaya yarar.

In [299]:
df_calisan.groupby("Departman")["Maaş"].mean()

Departman
Finans    33000.000000
Veri      38666.666667
İK        29000.000000
Name: Maaş, dtype: float64

In [307]:
df_calisan.groupby("Departman")["Maaş"].max()

Departman
Finans    34000
Veri      42000
İK        30000
Name: Maaş, dtype: int64

In [309]:
df_calisan.groupby("Departman")["Maaş"].min()

Departman
Finans    32000
Veri      35000
İK        28000
Name: Maaş, dtype: int64

In [311]:
# agg() >> birden fazla istatistiği tek seferde hesaplar

In [313]:
df_calisan.groupby("Departman")["Maaş"].agg("mean" , "max")

Departman
Finans    33000.000000
Veri      38666.666667
İK        29000.000000
Name: Maaş, dtype: float64

In [321]:
df_calisan.groupby("Departman")["Deneyim"].mean()

Departman
Finans    2.5
Veri      3.0
İK        1.5
Name: Deneyim, dtype: float64

In [333]:
df_calisan[df_calisan["Maaş"] > 35000]

     İsim Departman   Maaş  Deneyim
2  Zeynep      Veri  42000        4
5     Can      Veri  39000        3

# 6. Tabloları Birleştirme

In [344]:
#merge() >> ortak bilgiye göre birleştirme yapar
#concat() >> genellikle aynı sütunlara sahip tabloları alt alta veya yan yana eklemek için kullanılır

In [346]:
# Birinci tablo: Öğrenci bilgileri
ogrenciler = {
    "Ogrenci_ID": [101, 102, 103, 104],
    "İsim": ["Ayşe", "Mehmet", "Zeynep", "Ali"],
    "Bölüm": ["Matematik", "Fizik", "Matematik", "Kimya"]
}

df_ogrenci = pd.DataFrame(ogrenciler)

In [348]:
notlar = {
    "Ogrenci_ID": [101, 102, 103, 104],
    "Vize": [80, 65, 90, 70],
    "Final": [90, 75, 95, 60]
}

df_notlar = pd.DataFrame(notlar)

In [350]:
df_ogrenci

   Ogrenci_ID    İsim      Bölüm
0         101    Ayşe  Matematik
1         102  Mehmet      Fizik
2         103  Zeynep  Matematik
3         104     Ali      Kimya

In [352]:
df_notlar

   Ogrenci_ID  Vize  Final
0         101    80     90
1         102    65     75
2         103    90     95
3         104    70     60

In [364]:
pd.merge(df_ogrenci, df_notlar  , on = "Ogrenci_ID" )

   Ogrenci_ID    İsim      Bölüm  Vize  Final
0         101    Ayşe  Matematik    80     90
1         102  Mehmet      Fizik    65     75
2         103  Zeynep  Matematik    90     95
3         104     Ali      Kimya    70     60

In [366]:
sinif_a = pd.DataFrame({
    "İsim": ["Elif", "Can"],
    "Not": [85, 75]
})

sinif_b = pd.DataFrame({
    "İsim": ["Deniz", "Ece"],
    "Not": [90, 80]
})

In [374]:
pd.concat([sinif_a,sinif_b] , ignore_index= True) #ignore_index >> eski indeks numaralarını yok sayıp yeni sıralı indeksler oluşturmak için kullanılır

    İsim  Not
0   Elif   85
1    Can   75
2  Deniz   90
3    Ece   80

In [376]:
sinif_c = pd.DataFrame({
    "İsim": ["Merve", "Ahmet"],
    "Not": [88, 72]
})

sinif_d = pd.DataFrame({
    "İsim": ["Burak", "Selin"],
    "Not": [65, 95]
})

In [382]:
pd.concat([sinif_c , sinif_d] ,ignore_index = True)

    İsim  Not
0  Merve   88
1  Ahmet   72
2  Burak   65
3  Selin   95

In [384]:
ogrenciler = pd.DataFrame({
    "Ogrenci_ID": [1, 2, 3],
    "İsim": ["Ayşe", "Mehmet", "Zeynep"]
})

sinav_sonuclari = pd.DataFrame({
    "Ogrenci_ID": [1, 2, 3],
    "Not": [85, 70, 95]
})

In [386]:
pd.merge(ogrenciler,sinav_sonuclari , on = "Ogrenci_ID")

   Ogrenci_ID    İsim  Not
0           1    Ayşe   85
1           2  Mehmet   70
2           3  Zeynep   95

# 7. Pandas'ta Metin İşlemleri

In [389]:
df = pd.DataFrame({
    "İsim": ["AYŞE", "mehmet", "Zeynep", "ali"]
})

In [391]:
df

     İsim
0    AYŞE
1  mehmet
2  Zeynep
3     ali

In [395]:
df["İsim"].str.lower() #lower() >> bütün isimleri küçük harfe çevirir

0      ayşe
1    mehmet
2    zeynep
3       ali
Name: İsim, dtype: object

In [397]:
df["İsim"].str.upper() #upper() >> bütün isimleri büyük harfe çevirir

0      AYŞE
1    MEHMET
2    ZEYNEP
3       ALI
Name: İsim, dtype: object

In [401]:
df["İsim"].str.title() #title() >> bütün isimlerin ilk harfini büyük harfe çevirir

0      Ayşe
1    Mehmet
2    Zeynep
3       Ali
Name: İsim, dtype: object

In [407]:
df["İsim"].str.contains("a") #contains() >> belirli bir kelimenin/harfin bulunup bulunmadığını kontrol eder

0    False
1    False
2    False
3     True
Name: İsim, dtype: bool

In [411]:
 df["İsim"].str.contains("a" , case=False) #case>> büyük küçük harf ayrımı olmadan aramak istersek

0     True
1    False
2    False
3     True
Name: İsim, dtype: bool

In [413]:
df["İsim"].str.contains("e")

0    False
1     True
2     True
3    False
Name: İsim, dtype: bool

In [415]:
df = pd.DataFrame({
    "İsim": ["Ayşe", "Mehmet", "Zeynep", "Ali", "Ahmet"],
    "Bölüm": ["Matematik", "Fizik", "Matematik", "Kimya", "Fizik"]
})

In [417]:
df = pd.DataFrame({
    "Şehir": ["İstanbul", "Ankara", "İzmir"]
})

In [419]:
df["Şehir"].str.replace("a", "A") #str.replace() >> metin içerisinde belirli bir karakteri veya ifadeyi değiştirmek için kullanılır

0    İstAnbul
1      AnkArA
2       İzmir
Name: Şehir, dtype: object

In [429]:
df = pd.DataFrame({
    "İsim": [" Ayşe ", "Mehmet  ", " Zeynep"]
})

In [431]:
df["İsim"].str.strip() #str.strip() >> metinlerin başında ve sonundaki boşlukları temizler

0      Ayşe
1    Mehmet
2    Zeynep
Name: İsim, dtype: object

In [433]:
df_tarih = pd.DataFrame({
    "İsim": ["Ayşe", "Mehmet", "Zeynep"],
    "Tarih": ["2026-01-15", "2026-03-20", "2026-07-05"]
})

In [435]:
df_tarih.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   İsim    3 non-null      object
 1   Tarih   3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

In [445]:
df_tarih["Tarih"] = pd.to_datetime(df_tarih["Tarih"]) #to_datetima() >> tarihe dönüştürür object >> datetime

In [439]:
df_tarih

     İsim      Tarih
0    Ayşe 2026-01-15
1  Mehmet 2026-03-20
2  Zeynep 2026-07-05

In [441]:
df_tarih.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   İsim    3 non-null      object
 1   Tarih   3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes

In [465]:
df_siparis = pd.DataFrame({
    "Ürün": ["Bilgisayar", "Telefon", "Tablet"],
    "Sipariş_Tarihi": ["2026-02-10", "2026-04-15", "2026-06-22"]
})

In [461]:
df_siparis

         Ürün Sipariş_Tarihi
0  Bilgisayar     2026-02-10
1     Telefon     2026-04-15
2      Tablet     2026-06-22

In [467]:
df_siparis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Ürün            3 non-null      object
 1   Sipariş_Tarihi  3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

In [469]:
df_siparis["Sipariş_Tarihi"] = pd.to_datetime(df_siparis["Sipariş_Tarihi"])

In [471]:
df_siparis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Ürün            3 non-null      object
 1   Sipariş_Tarihi  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes

In [473]:
df_siparis["Sipariş_Tarihi"].dt.year

0    2026
1    2026
2    2026
Name: Sipariş_Tarihi, dtype: int32

In [475]:
df_siparis["Sipariş_Tarihi"].dt.month

0    2
1    4
2    6
Name: Sipariş_Tarihi, dtype: int32

In [477]:
df_siparis["Sipariş_Tarihi"].dt.day

0    10
1    15
2    22
Name: Sipariş_Tarihi, dtype: int32