In [1]:
import pandas as pd

In [48]:
import pandas as pd

data = {
    "Name": ["Ali", "Ayşe", "Mehmet", "Zeynep", "Elif", "Can"],
    "Department": ["IT", "HR", "IT", "Finans", "HR", "IT"],
    "Age": [24, 29, 32, 27, 23, 35],
    "Salary": [30000, 28000, 45000, 35000, 26000, 50000],
    "Experience": [1, 4, 7, 3, 1, 10]
}

df = pd.DataFrame(data)

In [50]:
df

     Name Department  Age  Salary  Experience
0     Ali         IT   24   30000           1
1    Ayşe         HR   29   28000           4
2  Mehmet         IT   32   45000           7
3  Zeynep     Finans   27   35000           3
4    Elif         HR   23   26000           1
5     Can         IT   35   50000          10

In [52]:
df.head(3)

     Name Department  Age  Salary  Experience
0     Ali         IT   24   30000           1
1    Ayşe         HR   29   28000           4
2  Mehmet         IT   32   45000           7

In [46]:
df.shape

(6, 5)

In [64]:
df[["Name" , "Salary"]]

     Name  Salary
0     Ali   30000
1    Ayşe   28000
2  Mehmet   45000
3  Zeynep   35000
4    Elif   26000
5     Can   50000

In [66]:
df[df["Age"] >= 25]

     Name Department  Age  Salary  Experience
1    Ayşe         HR   29   28000           4
2  Mehmet         IT   32   45000           7
3  Zeynep     Finans   27   35000           3
5     Can         IT   35   50000          10

In [68]:
df[df["Salary"] >= 30000]

     Name Department  Age  Salary  Experience
0     Ali         IT   24   30000           1
2  Mehmet         IT   32   45000           7
3  Zeynep     Finans   27   35000           3
5     Can         IT   35   50000          10

In [70]:
df.sort_values("Salary" , ascending = False)

     Name Department  Age  Salary  Experience
5     Can         IT   35   50000          10
2  Mehmet         IT   32   45000           7
3  Zeynep     Finans   27   35000           3
0     Ali         IT   24   30000           1
1    Ayşe         HR   29   28000           4
4    Elif         HR   23   26000           1

In [72]:
df.max()

Name          Zeynep
Department        IT
Age               35
Salary         50000
Experience        10
dtype: object

In [80]:
df["Salary"].mean()

35666.666666666664

In [82]:
df["Department"].value_counts()

Department
IT        3
HR        2
Finans    1
Name: count, dtype: int64

In [84]:
df.groupby("Department")["Salary"].mean()

Department
Finans    35000.000000
HR        27000.000000
IT        41666.666667
Name: Salary, dtype: float64

In [86]:
df["Experience"].max()

10

In [92]:
most_experienced = df.loc[df["Experience"].idxmax()]

In [94]:
print(most_experienced)

Name            Can
Department       IT
Age              35
Salary        50000
Experience       10
Name: 5, dtype: object

In [98]:
df[(df["Department"] == "IT") & (df["Age"] < 30)]

  Name Department  Age  Salary  Experience
0  Ali         IT   24   30000           1

In [100]:
df[(df["Department"]== "HR") | (df["Experience"] > 5) ]

     Name Department  Age  Salary  Experience
1    Ayşe         HR   29   28000           4
2  Mehmet         IT   32   45000           7
4    Elif         HR   23   26000           1
5     Can         IT   35   50000          10

In [102]:
df["Bonus"] = df["Experience"] * 2000

In [104]:
df

     Name Department  Age  Salary  Experience  Bonus
0     Ali         IT   24   30000           1   2000
1    Ayşe         HR   29   28000           4   8000
2  Mehmet         IT   32   45000           7  14000
3  Zeynep     Finans   27   35000           3   6000
4    Elif         HR   23   26000           1   2000
5     Can         IT   35   50000          10  20000

In [112]:
df.loc[df["Age"].idxmin()]

Name           Elif
Department       HR
Age              23
Salary        26000
Experience        1
Bonus          2000
Name: 4, dtype: object