In [1]:
import pandas as pd

In [3]:
import numpy as np

In [33]:
data = {
    "Sehir": ["İstanbul", "Ankara", "İzmir", "Bursa", "Antalya", "Erzurum", "Trabzon"],
    "Bolge": ["Marmara", "İç Anadolu", "Ege", "Marmara", "Akdeniz", None, "Karadeniz"],
    "Nufus": [15840000, 5800000, np.nan, 3100000, 2600000, 750000, np.nan],
    "Ortalama_Sicaklik": [15.2, 12.0, 17.8, 14.5, np.nan, 6.0, 14.6],
    "Yillik_Turist": [16000000, 1200000, 3000000, 2000000, 15000000, 400000, 1800000]
}

df = pd.DataFrame(data)

In [35]:
df

      Sehir       Bolge       Nufus  Ortalama_Sicaklik  Yillik_Turist
0  İstanbul     Marmara  15840000.0               15.2       16000000
1    Ankara  İç Anadolu   5800000.0               12.0        1200000
2     İzmir         Ege         NaN               17.8        3000000
3     Bursa     Marmara   3100000.0               14.5        2000000
4   Antalya     Akdeniz   2600000.0                NaN       15000000
5   Erzurum        None    750000.0                6.0         400000
6   Trabzon   Karadeniz         NaN               14.6        1800000

In [37]:
df.isnull().sum()

Sehir                0
Bolge                1
Nufus                2
Ortalama_Sicaklik    1
Yillik_Turist        0
dtype: int64

In [39]:
df.dropna()

      Sehir       Bolge       Nufus  Ortalama_Sicaklik  Yillik_Turist
0  İstanbul     Marmara  15840000.0               15.2       16000000
1    Ankara  İç Anadolu   5800000.0               12.0        1200000
3     Bursa     Marmara   3100000.0               14.5        2000000

In [41]:
df["Ortalama_Sicaklik"].mean()

13.35

In [55]:
df["Ortalama_Sicaklik"] = df["Ortalama_Sicaklik"].fillna(df["Ortalama_Sicaklik"].mean())

In [57]:
df

      Sehir       Bolge       Nufus  Ortalama_Sicaklik  Yillik_Turist
0  İstanbul     Marmara  15840000.0              15.20       16000000
1    Ankara  İç Anadolu   5800000.0              12.00        1200000
2     İzmir         Ege         NaN              17.80        3000000
3     Bursa     Marmara   3100000.0              14.50        2000000
4   Antalya     Akdeniz   2600000.0              13.35       15000000
5   Erzurum  Bilinmiyor    750000.0               6.00         400000
6   Trabzon   Karadeniz         NaN              14.60        1800000

In [47]:
df["Bolge"] = df["Bolge"].fillna("Bilinmiyor")

In [21]:
df

      Sehir       Bolge       Nufus  Ortalama_Sicaklik  Yillik_Turist
0  İstanbul     Marmara  15840000.0               15.2       16000000
1    Ankara  İç Anadolu   5800000.0               12.0        1200000
2     İzmir         Ege         NaN               17.8        3000000
3     Bursa     Marmara   3100000.0               14.5        2000000
4   Antalya     Akdeniz   2600000.0                NaN       15000000
5   Erzurum  Bilinmiyor    750000.0                6.0         400000
6   Trabzon   Karadeniz         NaN               14.6        1800000

In [61]:
df.sort_values(by = "Sehir" , ascending = True)

      Sehir       Bolge       Nufus  Ortalama_Sicaklik  Yillik_Turist
1    Ankara  İç Anadolu   5800000.0              12.00        1200000
4   Antalya     Akdeniz   2600000.0              13.35       15000000
3     Bursa     Marmara   3100000.0              14.50        2000000
5   Erzurum  Bilinmiyor    750000.0               6.00         400000
6   Trabzon   Karadeniz         NaN              14.60        1800000
0  İstanbul     Marmara  15840000.0              15.20       16000000
2     İzmir         Ege         NaN              17.80        3000000

In [67]:
df_sirali = df.sort_values(by = "Nufus" , ascending = False)

In [69]:
df_sirali

      Sehir       Bolge       Nufus  Ortalama_Sicaklik  Yillik_Turist
0  İstanbul     Marmara  15840000.0              15.20       16000000
1    Ankara  İç Anadolu   5800000.0              12.00        1200000
3     Bursa     Marmara   3100000.0              14.50        2000000
4   Antalya     Akdeniz   2600000.0              13.35       15000000
5   Erzurum  Bilinmiyor    750000.0               6.00         400000
2     İzmir         Ege         NaN              17.80        3000000
6   Trabzon   Karadeniz         NaN              14.60        1800000

In [72]:
df_sirali = df_sirali.reset_index(drop=True)

In [74]:
df_sirali

      Sehir       Bolge       Nufus  Ortalama_Sicaklik  Yillik_Turist
0  İstanbul     Marmara  15840000.0              15.20       16000000
1    Ankara  İç Anadolu   5800000.0              12.00        1200000
2     Bursa     Marmara   3100000.0              14.50        2000000
3   Antalya     Akdeniz   2600000.0              13.35       15000000
4   Erzurum  Bilinmiyor    750000.0               6.00         400000
5     İzmir         Ege         NaN              17.80        3000000
6   Trabzon   Karadeniz         NaN              14.60        1800000

In [77]:
import pandas as pd
import numpy as np

data = {
    "Universite": ["ODTÜ", "İTÜ", "Boğaziçi", "Hacettepe", "Ege", "Anadolu", "Yıldız Teknik"],
    "Sehir": ["Ankara", "İstanbul", "İstanbul", "Ankara", "İzmir", None, "İstanbul"],
    "Ogrenci_Sayisi": [27000, 38000, np.nan, 50000, 55000, 22000, np.nan],
    "Kurulus_Yili": [1956, 1773, 1863, 1967, np.nan, 1958, 1911],
    "Akademisyen_Sayisi": [2500, 3100, 1200, 3500, 3000, 1500, 2100]
}

df = pd.DataFrame(data)

In [79]:
df

      Universite     Sehir  Ogrenci_Sayisi  Kurulus_Yili  Akademisyen_Sayisi
0           ODTÜ    Ankara         27000.0        1956.0                2500
1            İTÜ  İstanbul         38000.0        1773.0                3100
2       Boğaziçi  İstanbul             NaN        1863.0                1200
3      Hacettepe    Ankara         50000.0        1967.0                3500
4            Ege     İzmir         55000.0           NaN                3000
5        Anadolu      None         22000.0        1958.0                1500
6  Yıldız Teknik  İstanbul             NaN        1911.0                2100

In [81]:
df.isnull().sum()

Universite            0
Sehir                 1
Ogrenci_Sayisi        2
Kurulus_Yili          1
Akademisyen_Sayisi    0
dtype: int64

In [83]:
df["Sehir"] = df["Sehir"].fillna("Bilinmiyor")

In [85]:
df

      Universite       Sehir  Ogrenci_Sayisi  Kurulus_Yili  Akademisyen_Sayisi
0           ODTÜ      Ankara         27000.0        1956.0                2500
1            İTÜ    İstanbul         38000.0        1773.0                3100
2       Boğaziçi    İstanbul             NaN        1863.0                1200
3      Hacettepe      Ankara         50000.0        1967.0                3500
4            Ege       İzmir         55000.0           NaN                3000
5        Anadolu  Bilinmiyor         22000.0        1958.0                1500
6  Yıldız Teknik    İstanbul             NaN        1911.0                2100

In [87]:
df["Ogrenci_Sayisi"].mean()

38400.0

In [89]:
df["Ogrenci_Sayisi"] = df["Ogrenci_Sayisi"].fillna(df["Ogrenci_Sayisi"].mean())

In [91]:
df

      Universite       Sehir  Ogrenci_Sayisi  Kurulus_Yili  Akademisyen_Sayisi
0           ODTÜ      Ankara         27000.0        1956.0                2500
1            İTÜ    İstanbul         38000.0        1773.0                3100
2       Boğaziçi    İstanbul         38400.0        1863.0                1200
3      Hacettepe      Ankara         50000.0        1967.0                3500
4            Ege       İzmir         55000.0           NaN                3000
5        Anadolu  Bilinmiyor         22000.0        1958.0                1500
6  Yıldız Teknik    İstanbul         38400.0        1911.0                2100

In [93]:
df = df.dropna(subset = ["Kurulus_Yili"]) #subset=["Sütun_Adı"]: Tüm satırı silmek için sadece belirtilen sütun(lar)daki NaN değerleri dikkate alır. 
#Diğer sütunlardaki eksik verilerden dolayı satırın silinmesini engeller.

In [95]:
df

      Universite       Sehir  Ogrenci_Sayisi  Kurulus_Yili  Akademisyen_Sayisi
0           ODTÜ      Ankara         27000.0        1956.0                2500
1            İTÜ    İstanbul         38000.0        1773.0                3100
2       Boğaziçi    İstanbul         38400.0        1863.0                1200
3      Hacettepe      Ankara         50000.0        1967.0                3500
5        Anadolu  Bilinmiyor         22000.0        1958.0                1500
6  Yıldız Teknik    İstanbul         38400.0        1911.0                2100