In [1]:
import pandas as pd

In [34]:
data = {
    "Musteri": ["  Ali Yılmaz ", "AYŞE KAYA", "mehmet demir", "Zeynep Çelik ", "can  yıldız"],
    "Sehir": ["İstanbul", "ANKARA", "izmir", "İstanbul", "Ankara"],
    "Eposta": ["ali.yilmaz@gmail.com", "ayse.kaya@HOTMAIL.COM", "mehmet@yahoo.com", "zeynep@gmail.com", "can@gmail.com"],
    "Telefon": ["0532-111-2233", "0505-222-3344", "0542-333-4455", "0533-444-5566", "0555-555-6677"]
}

df = pd.DataFrame(data)

In [3]:
df

         Musteri     Sehir                 Eposta        Telefon
0    Ali Yılmaz   İstanbul   ali.yilmaz@gmail.com  0532-111-2233
1      AYŞE KAYA    ANKARA  ayse.kaya@HOTMAIL.COM  0505-222-3344
2   mehmet demir     izmir       mehmet@yahoo.com  0542-333-4455
3  Zeynep Çelik   İstanbul       zeynep@gmail.com  0533-444-5566
4    can  yıldız    Ankara          can@gmail.com  0555-555-6677

In [4]:
df["Sehir"] = df["Sehir"].str.upper()

In [5]:
df

         Musteri     Sehir                 Eposta        Telefon
0    Ali Yılmaz   İSTANBUL   ali.yilmaz@gmail.com  0532-111-2233
1      AYŞE KAYA    ANKARA  ayse.kaya@HOTMAIL.COM  0505-222-3344
2   mehmet demir     IZMIR       mehmet@yahoo.com  0542-333-4455
3  Zeynep Çelik   İSTANBUL       zeynep@gmail.com  0533-444-5566
4    can  yıldız    ANKARA          can@gmail.com  0555-555-6677

In [6]:
df["Telefon"].str.replace("-" , "")

0    05321112233
1    05052223344
2    05423334455
3    05334445566
4    05555556677
Name: Telefon, dtype: object

In [7]:
df[df["Eposta"].str.contains("gmail" , case = False)]

         Musteri     Sehir                Eposta        Telefon
0    Ali Yılmaz   İSTANBUL  ali.yilmaz@gmail.com  0532-111-2233
3  Zeynep Çelik   İSTANBUL      zeynep@gmail.com  0533-444-5566
4    can  yıldız    ANKARA         can@gmail.com  0555-555-6677

In [8]:
 df["Musteri"]= df["Musteri"].str.strip().str.title()

In [9]:
df

        Musteri     Sehir                 Eposta        Telefon
0    Ali Yılmaz  İSTANBUL   ali.yilmaz@gmail.com  0532-111-2233
1     Ayşe Kaya    ANKARA  ayse.kaya@HOTMAIL.COM  0505-222-3344
2  Mehmet Demir     IZMIR       mehmet@yahoo.com  0542-333-4455
3  Zeynep Çelik  İSTANBUL       zeynep@gmail.com  0533-444-5566
4   Can  Yıldız    ANKARA          can@gmail.com  0555-555-6677

In [10]:
import pandas as pd

katalog = {
    "Urun_Kodu": [" PRD-101 ", "prd-102", "PRD-103 ", "PRD-104", " prd-105 "],
    "Urun_Adi": ["Kablosuz Kulaklık", "MEKANİK KLAVYE", "Bluetooth Hoparlör", "Oyuncu Mouse", "Akıllı Saat"],
    "Kategori": ["Elektronik > Ses", "Elektronik > Bilgisayar", "Elektronik > Ses", "Elektronik > Bilgisayar", "Elektronik > Aksesuar"],
    "Fiyat_TL": ["1.250 TL", "2.100 TL", "850 TL", "600 TL", "3.400 TL"]
}

df_urun = pd.DataFrame(katalog)

In [11]:
df_urun

   Urun_Kodu            Urun_Adi                 Kategori  Fiyat_TL
0   PRD-101    Kablosuz Kulaklık         Elektronik > Ses  1.250 TL
1    prd-102      MEKANİK KLAVYE  Elektronik > Bilgisayar  2.100 TL
2   PRD-103   Bluetooth Hoparlör         Elektronik > Ses    850 TL
3    PRD-104        Oyuncu Mouse  Elektronik > Bilgisayar    600 TL
4   prd-105          Akıllı Saat    Elektronik > Aksesuar  3.400 TL

In [12]:
df_urun["Urun_Kodu"] = df_urun["Urun_Kodu"].str.strip().str.upper()

In [13]:
df_urun

  Urun_Kodu            Urun_Adi                 Kategori  Fiyat_TL
0   PRD-101   Kablosuz Kulaklık         Elektronik > Ses  1.250 TL
1   PRD-102      MEKANİK KLAVYE  Elektronik > Bilgisayar  2.100 TL
2   PRD-103  Bluetooth Hoparlör         Elektronik > Ses    850 TL
3   PRD-104        Oyuncu Mouse  Elektronik > Bilgisayar    600 TL
4   PRD-105         Akıllı Saat    Elektronik > Aksesuar  3.400 TL

In [14]:
df_urun["Fiyat_TL"] = df_urun["Fiyat_TL"].str.replace(".",  "").str.replace("TL" , "")

In [15]:
df_urun

  Urun_Kodu            Urun_Adi                 Kategori Fiyat_TL
0   PRD-101   Kablosuz Kulaklık         Elektronik > Ses    1250
1   PRD-102      MEKANİK KLAVYE  Elektronik > Bilgisayar    2100
2   PRD-103  Bluetooth Hoparlör         Elektronik > Ses     850
3   PRD-104        Oyuncu Mouse  Elektronik > Bilgisayar     600
4   PRD-105         Akıllı Saat    Elektronik > Aksesuar    3400

In [32]:
df_urun["Kategori"].str.contains("ses" , case = False)

0     True
1    False
2     True
3    False
4     True
Name: Kategori, dtype: bool